version: '3.7'
services:
  sr-traefik:
    image: traefik:latest
    volumes:
      - ./dockersettings/traefik.yml:/etc/traefik/traefik.yml # v2 settings
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/etc/traefik/acme
      - ./letsencrypt:/letsencrypt
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    # environment:
    #   - WAIT_HOSTS=sr-api:4000, sr-frontend:3000
  sr-frontend:
    init: true
    image: frontend:latest
    ports:
      - 3000:3000
    deploy:
      labels:
        - traefik.http.services.sr-frontend-service.loadBalancer.servers.port=3000
        - traefik.http.routers.sr-frontend-router-http.service=sr-frontend-service
        - traefik.http.routers.sr-frontend-router-http.entryPoints=web
        - traefik.http.routers.sr-frontend-router-http.rule=Host(`sungryeol.xyz`)
        - traefik.http.routers.sr-frontend-router-https.service=sr-frontend-service
        - traefik.http.routers.sr-frontend-router-https.entryPoints=web-secure
        - traefik.http.routers.sr-frontend-router-https.rule=Host(`sungryeol.xyz`)
        - traefik.http.routers.sr-frontend-router-https.tls.certResolver=sr-cert

    
  db:
    image: mongo:4.2.0-bionic
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - db-mongo:/data/db
  
  sr-api:
    image: api:latest
    init: true
    ports:
      - 4000:4000
    environment:
      - MONGO_URI=db:27017  # use container name for network
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
    deploy:
      labels:
        - traefik.http.services.sr-api-service=loadBalancer.servers.port=4000
        - traefik.http.routers.sr-api-router-http.service=sr-api-service
        - traefik.http.routers.sr-api-router-http.entryPoints=web
        - traefik.http.routers.sr-api-router-http.rule=Host(`api.sungryeol.xyz`)
        - traefik.http.routers.sr-api-router-https.service=sr-api-service
        - traeifk.http.routers.sr-api-router-https.entryPoints=web-secure
        - traefik.http.routers.sr-api-router-https.rule=Host(`api.sungryeol.xyz`)
        - traefik.http.routers.sr-frontend-router-https.tls.certResolver=sr-cert

  
volumes:
  db-mongo:
  acme: